---
apiVersion: v1
kind: Secret
metadata:
  name: horus-credential
  namespace: horus-operator-system
stringData:
  RESTIC_PASSWORD: "restic"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
