apiVersion: storage.hybfkuf.io/v1alpha1
kind: Backup
metadata:
  name: nginx-deploy-local
spec:
  schedule: "*/1 * * * *"
  backupFrom:
    resource: deployment
    name: nginx-deploy-local
  backupTo:
    nfs:
      server: 10.250.16.21
      path: /srv/nfs/restic
    minio:
      endpoint:
        scheme: http
        address: 10.250.16.21
        port: 9000
      bucket: restic
  timezone: Asia/Shanghai
  timeout: 10m
  cluster: mycluster
  credentialName: horus-credential
  logLevel: info
  #logLevel: debug
  logFormat: text
  #logFormat: json
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
