# permissions for end users to edit traffics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-editor-role
rules:
- apiGroups:
  - networking.hybfkuf.io
  resources:
  - traffics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.hybfkuf.io
  resources:
  - traffics/status
  verbs:
  - get
