# permissions for end users to edit migrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-editor-role
rules:
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - migrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - migrations/status
  verbs:
  - get
