# permissions for end users to view clones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clone-viewer-role
rules:
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - clones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - clones/status
  verbs:
  - get
