apiVersion: storage.hybfkuf.io/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  schedule: "*/1 * * * *"
  backupFrom:
    resource: statefulset
    name: nginx-sts
  backupTo:
    nfs:
      server: 10.240.1.21
      path: /srv/nfs/restic
    minio:
      endpoint:
        scheme: http
        address: 10.240.1.21
        port: 9000
      bucket: restic
      credentialName: minio-credential
  timezone: 'Asia/Shanghai'
  timeout: 10m
  cluster: mycluster
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credential
  namespace: horus-operator
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RESTIC_PASSWORD: "restic"
