apiVersion: storage.hybfkuf.io/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  schedule: "*/1 * * * *"
  backupFrom:
    resource: pod
    name: k8s-tools
  backupTo:
    nfs:
      server: 1.1.1.1
      path: /srv/nfs/kubedata
