apiVersion: storage.hybfkuf.io/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  schedule: "*/1 * * * *"
  backupFrom:
    resource: deployment
    name: nginx-deploy
  backupTo:
    nfs:
      server: 10.250.16.21
      path: /srv/nfs/restic
  timezone: 'Asia/Shanghai'
  timeout: 10m
