apiVersion: v1
kind: ServiceAccount
metadata:
  name: horusctl
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horusctl
rules:
- apiGroups:
  - storage.hybfkuf.io
  - networking.hybfkuf.io
  resources:
  - backups
  - restores
  - clones
  - migrations
  - traffics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.hybfkuf.io
  - networking.hybfkuf.io
  resources:
  - backups/status
  - restores/status
  - clones/status
  - migrations/status
  - traffics/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - apps
  - ""
  resources:
  - statefulsets
  - daemonsets
  - replicasets
  - pods
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
# 在 pod 执行命令的权限
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - create
# 获取 pod 命令的输出结果的权限
- apiGroups:
  - ""
  resources:
  - pods/logs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: horusctl
subjects:
- kind: ServiceAccount
  name: horusctl
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: horusctl
  #name: cluster-admin
