apiVersion: v1
kind: ServiceAccount
metadata:
  name: horusctl
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: horusctl
rules:
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - apps
  - ""
  resources:
  - statefulset
  - daemonset
  - replicasets
  - pods
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - create
- apiGroups:
  - storage.hybfkuf.io
  resources:
  - backups/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: horusctl
subjects:
- kind: ServiceAccount
  name: horusctl
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: horusctl
